apiVersion: argoproj.io/v1alpha1
king: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hellseyfer/argocd-example-apps
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: *
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
